# Edit these paths when you copy the module
subdir = src/test/perl/example_suite
top_builddir = ../../../..

include $(top_builddir)/src/Makefile.global

check:
	$(prove_check)

clean:
	rm -rf ./tmp_check
